# Generated by Django 2.0.5 on 2019-06-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='admin', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
