# Generated by Django 2.0.5 on 2019-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20190501_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
        migrations.AddField(
            model_name='events',
            name='cor',
            field=models.CharField(choices=[('#FFD700', 'Amarelo'), ('#0071c5', 'Azul Turquesa'), ('#FF4500', 'Laranja'), ('#8B4513', 'Marrom'), ('#1C1C1C', 'Preto'), ('#436EEE', 'Royal Blue'), ('#A020F0', 'Roxo'), ('#40E0D0', 'Turquesa'), ('#228B22', 'Verde'), ('#8B0000', 'Vermelho')], default='#0071c5', max_length=10),
        ),
    ]
