# Generated by Django 2.0.5 on 2019-06-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190501_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('view_evento_agenda', 'Can view evento'),), 'verbose_name': 'Evento na Agenda'},
        ),
    ]
