# Generated by Django 2.0.5 on 2019-06-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190621_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('view_eventoagenda', 'Can view evento agenda'),), 'verbose_name': 'Evento na Agenda'},
        ),
    ]
