# Generated by Django 2.0.5 on 2019-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190621_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('view_events', 'Can view evento agenda'), ('utilizar_events', 'Pode utilizar agenda')), 'verbose_name': 'Agenda'},
        ),
    ]
