# Generated by Django 2.0.5 on 2019-06-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20190621_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('view_events', 'Can view evento agenda'), ('acesso_events', 'Pode acessar a agenda')), 'verbose_name': 'Agenda'},
        ),
    ]
