# Generated by Django 2.0.5 on 2019-06-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20190621_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('acesso_events', 'Pode acessar a agenda'),), 'verbose_name': 'Agenda'},
        ),
    ]
