# Generated by Django 2.0.5 on 2019-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('0', 'Consumidor Final'), ('1', 'Garantia'), ('2', 'Remessa'), ('3', 'Venda Externa'), ('4', 'Venda Loja'), ('5', 'Venda de Materiais e Serviços'), ('6', 'Vendas Site')], max_length=1, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('probabilidade_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contato', models.CharField(blank=True, max_length=255, null=True)),
                ('origem', models.CharField(blank=True, choices=[('IE', 'Indicação Externa'), ('II', 'Indicação Interna'), ('BB', 'Boca a Boca'), ('WE', 'Web'), ('PA', 'Parceiro'), ('CA', 'Campanha'), ('LO', 'Loja'), ('PV', 'Ponto de Venda Externo'), ('RA', 'Rádio'), ('JI', 'Jornal Impressp'), ('OU', 'Outro')], max_length=2, null=True)),
                ('nome_origem', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(choices=[('0', 'Concluída com sucesso'), ('1', 'Cancelado'), ('2', 'Em andamento')], default=2, max_length=1)),
                ('data_sucesso', models.DateField(blank=True, null=True)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=1000, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade_cliente', to='cadastro.Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade_empresa', to='cadastro.Empresa')),
                ('status_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade_status_venda', to='cadastro.StatusVenda')),
            ],
        ),
    ]
