# Generated by Django 2.0.5 on 2019-05-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm2', '0003_oportunidade_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='crm2.Etiqueta'),
        ),
    ]
