# Generated by Django 2.0.5 on 2019-06-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm2', '0004_auto_20190514_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'permissions': (('view_etiqueta', 'Can view etiqueta'),), 'verbose_name': 'Etiqueta'},
        ),
    ]
