# Generated by Django 2.0.5 on 2019-06-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm2', '0005_auto_20190621_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidade',
            options={'permissions': (('view_oportunidade', 'Can view oportunidade'),), 'verbose_name': 'Oportunidade'},
        ),
    ]
