# Generated by Django 2.0.5 on 2019-06-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm2', '0006_auto_20190621_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidade',
            options={'permissions': (('view_oportunidade', 'Can view oportunidade'), ('acesso_navegacao', 'Pode acessar a navegacao'), ('acesso_funil', 'Pode acessar o funil')), 'verbose_name': 'Oportunidade'},
        ),
    ]
