# Generated by Django 2.0.5 on 2019-06-17 16:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190502_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='venda',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='mod_frete',
            field=models.CharField(choices=[('0', 'Por conta do remetente'), ('1', 'Por conta do destinatário'), ('2', 'Por conta de terceiros'), ('3', 'Transporte próprio do remetente'), ('4', 'Transporte próprio do destinatário'), ('9', 'Sem frete')], default='9', max_length=1),
        ),
    ]
