# Generated by Django 2.0.5 on 2019-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20190617_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='especie_transporte',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='marca_transporte',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='volumes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
