# Generated by Django 2.0.5 on 2019-05-01 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import SGEO.apps.login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesDoPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotaAdicionalPlano',
            fields=[
                ('quantidade', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=13)),
                ('qtd_notas', models.PositiveIntegerField()),
                ('qtd_usuarios', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_foto', models.ImageField(blank=True, default='imagens/user.png', upload_to=SGEO.apps.login.models.user_directory_path)),
                ('user_capa_foto', models.ImageField(blank=True, default='imagens/background-user.png', upload_to=SGEO.apps.login.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdicionalPlano',
            fields=[
                ('quantidade', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.AddField(
            model_name='configuracoesdoplano',
            name='notas_adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_adicional', to='login.NotaAdicionalPlano'),
        ),
        migrations.AddField(
            model_name='configuracoesdoplano',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='login.Plano'),
        ),
        migrations.AddField(
            model_name='configuracoesdoplano',
            name='usuarios_adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_adicional', to='login.UsuarioAdicionalPlano'),
        ),
    ]
