# Generated by Django 2.0.5 on 2019-05-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='codigo_parceiro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='cupom_desconto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='cupons_utilizados',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
