# Generated by Django 2.0.5 on 2019-08-14 12:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20190702_2151'),
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensVendaPdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_pdv_produto', to='cadastro.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='VendaPdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, max_length=60, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pagamento', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('0', 'Aberto'), ('1', 'Faturado')], default='0', max_length=1)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_pdv_cliente', to='cadastro.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='itensvendapdv',
            name='venda_pdv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda_pdv', to='pdv.VendaPdv'),
        ),
    ]
