# Generated by Django 2.0.5 on 2019-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_auto_20190814_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendapdv',
            name='data_emissao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
