# Generated by Django 2.0.5 on 2019-05-01 23:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custos', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(choices=[('0', 'Ativo'), ('1', 'Inativo')], default='0', max_length=1)),
                ('dia_vencimento', models.PositiveIntegerField()),
                ('duracao_contrato', models.PositiveIntegerField()),
                ('tipo_duracao_contrato', models.CharField(choices=[('0', 'Dias'), ('1', 'Semanas'), ('2', 'Meses'), ('3', 'Anos')], default=0, max_length=1)),
                ('ultimo_reajuste', models.DateField(blank=True, null=True)),
                ('proximo_reajuste', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField()),
                ('dias_carencia', models.PositiveIntegerField()),
                ('valor_periodo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('numero_parcelas', models.PositiveIntegerField()),
                ('intervalo', models.CharField(choices=[('0', 'Dias'), ('1', 'Meses'), ('2', 'Outro Período')], default=0, max_length=1)),
                ('periodo', models.CharField(choices=[('0', '07/14 dias'), ('1', '14/28 dias'), ('2', '15/30 dias'), ('3', '21/28 dias'), ('4', '21/42 dias'), ('5', '28/42 dias'), ('6', '28/56 dias'), ('7', '28/35 dias'), ('8', '30/60 dias'), ('9', '30/40/50 dias'), ('10', '35/42 dias'), ('11', '35/70 dias'), ('12', '42/84 dias'), ('13', '45/90 dias'), ('14', '56/102 dias'), ('15', '90/180 dias'), ('16', 'Outros')], default=0, max_length=2)),
                ('intervalo_dias', models.PositiveIntegerField()),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('comissao_vendedor', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_comissao_vendedor_periodo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_comissao_vendedor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_cliente', to='cadastro.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
