# Generated by Django 2.0.5 on 2019-06-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20190502_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'permissions': (('view_contrato', 'Can view contrato'),), 'verbose_name': 'Contrato'},
        ),
    ]
