# Generated by Django 2.0.5 on 2019-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_financeira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoIntegracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('plataforma', models.CharField(choices=[('HM', 'Hotmart'), ('ED', 'Eduzz'), ('MP', 'Mercado Pago'), ('PS', 'PagSeguro'), ('CI', 'Cielo')], max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='pagseguro',
            old_name='api_key',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pagseguro',
            old_name='public_key',
            new_name='token',
        ),
    ]
