# Generated by Django 2.0.5 on 2019-05-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_financeira', '0002_auto_20190515_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodointegracao',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('HM', 'Hotmart'), ('ED', 'Eduzz'), ('MP', 'Mercado Pago'), ('PS', 'PagSeguro'), ('CI', 'Cielo')], max_length=2, null=True),
        ),
    ]
