# Generated by Django 2.0.5 on 2019-06-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_financeira', '0003_auto_20190517_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduzz',
            options={'permissions': (('acessar_eduzz', 'Acessar Eduzz'),), 'verbose_name': 'Integração Eduzz'},
        ),
        migrations.AlterModelOptions(
            name='hotmart',
            options={'permissions': (('acessar_hotmart', 'Acessar Hotmart'),), 'verbose_name': 'Integração Hotmart'},
        ),
        migrations.AlterModelOptions(
            name='mercadopago',
            options={'permissions': (('acessar_mp', 'Acessar Mercado Pago'),), 'verbose_name': 'Integração Mercado Pago'},
        ),
        migrations.AlterModelOptions(
            name='pagseguro',
            options={'permissions': (('acessar_ps', 'Acessar Pagseguro'),), 'verbose_name': 'Integração Pagseguro'},
        ),
    ]
