# Generated by Django 2.0.5 on 2019-06-04 22:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20190501_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_total_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
