# Generated by Django 2.0.5 on 2019-06-09 02:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cliente_valor_total_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_vendida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
