# Generated by Django 2.0.5 on 2019-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_produto_quantidade_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
