# Generated by Django 2.0.5 on 2019-07-03 00:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20190702_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('validade', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Lote',
                'permissions': (('view_lote', 'Can view lote'),),
            },
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='data_vencimento',
            new_name='validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
        migrations.AddField(
            model_name='produto',
            name='controlado_por_lote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='cadastro.Produto'),
        ),
    ]
