# Generated by Django 2.0.5 on 2019-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('compras', '0002_auto_20190501_2039'),
        ('vendas', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saida_estoque', to='vendas.PedidoVenda'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_estoque_fornecedor', to='cadastro.Fornecedor'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_estoque_local', to='estoque.LocalEstoque'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_estoque_pedido', to='compras.PedidoCompra'),
        ),
    ]
