# Generated by Django 2.0.5 on 2019-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletos', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagador_boleto', to='cadastro.Cliente'),
        ),
    ]
