# Generated by Django 2.0.5 on 2019-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletos', '0002_boleto_pagador'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='pedido_de_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_boleto', to='vendas.PedidoVenda'),
        ),
    ]
