# Generated by Django 2.0.5 on 2019-05-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='natop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_op', to='fiscal.NaturezaOperacao'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='versao',
            field=models.CharField(choices=[('4.0', 'v4.0')], default='4.0', max_length=4),
        ),
    ]
