# Generated by Django 2.0.5 on 2019-05-01 23:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'permissions': (('view_centrocusto', 'Can view centro de custo'),),
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('depreciacao_bem', models.CharField(blank=True, choices=[('1', 'Aparelhos e Instrumentos'), ('2', 'Caixas, Formas, Moldes, e Vasilhames'), ('3', 'Eletrônicos'), ('4', 'Equipamentos de Comunicação'), ('5', 'Imóveis, Edifícios e Benfeitorias'), ('6', 'Ferramentas e Dispositivos'), ('7', 'Instalações'), ('8', 'Máquinas e Equipamentos'), ('9', 'Máquinas e Equipamentos Usados'), ('10', 'Móveis e Utensílios'), ('11', 'Veículos'), ('12', 'Veículos Usados'), ('13', 'Outros')], max_length=2, null=True)),
                ('depreciacao_anos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('abatimento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('movimentar_caixa', models.BooleanField(default=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/lancamentos/')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'permissions': (('view_lancamento', 'Can view lancamento'),),
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'permissions': (('acesso_fluxodecaixa', 'Pode acessar o Fluxo de Caixa'),),
            },
        ),
        migrations.CreateModel(
            name='PlanoContasGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('tipo_grupo', models.CharField(choices=[('0', 'Entrada'), ('1', 'Saída')], max_length=1)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo do Plano de Contas',
                'permissions': (('view_planocontasgrupo', 'Can view plano contas'),),
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('lancamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Lancamento')),
                ('status', models.CharField(choices=[('0', 'Recebida'), ('1', 'A receber'), ('2', 'Atrasada')], default='1', max_length=1)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_cliente', to='cadastro.Cliente')),
            ],
            bases=('financeiro.lancamento',),
        ),
        migrations.CreateModel(
            name='PlanoContasSubgrupo',
            fields=[
                ('planocontasgrupo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PlanoContasGrupo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='financeiro.PlanoContasGrupo')),
            ],
            bases=('financeiro.planocontasgrupo',),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('lancamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Lancamento')),
                ('status', models.CharField(choices=[('0', 'Paga'), ('1', 'A pagar'), ('2', 'Atrasada')], default='1', max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_fornecedor', to='cadastro.Fornecedor')),
                ('grupo_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_plano_pagamento', to='financeiro.PlanoContasGrupo')),
            ],
            bases=('financeiro.lancamento',),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centro_custo', to='financeiro.CentroCusto'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='conta_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_corrente_conta', to='cadastro.Banco'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='movimento_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_caixa_lancamento', to='financeiro.MovimentoCaixa'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='grupo_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_plano_recebimento', to='financeiro.PlanoContasGrupo'),
        ),
    ]
