# Generated by Django 2.0.5 on 2019-05-04 15:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='parcela_atual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='valor_parcelado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
