# Generated by Django 2.0.5 on 2019-05-04 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20190504_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='parcelas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
