# Generated by Django 2.0.5 on 2019-05-04 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20190504_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='dia_pagamento',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='flag_dia_pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='recorrencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
