# Generated by Django 2.0.5 on 2019-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20190504_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='primeiro_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
