# Generated by Django 2.0.5 on 2019-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamento_primeiro_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='dia_pagamento',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='flag_dia_pagamento',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo_recorrencia',
            field=models.CharField(choices=[('1', 'Dias'), ('2', 'Meses'), ('3', 'Anos')], default='1', max_length=1),
        ),
    ]
