# Generated by Django 2.0.5 on 2019-05-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20190504_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='primeiro_pagamento',
            field=models.DateField(),
        ),
    ]
