# Generated by Django 2.0.5 on 2019-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20190504_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='valor_parcelado',
        ),
    ]
