# Generated by Django 2.0.5 on 2019-05-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_remove_lancamento_valor_parcelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='parcela_atual',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='primeiro_pagamento',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='recorrencia',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='tipo_recorrencia',
        ),
    ]
