# Generated by Django 2.0.5 on 2019-05-06 21:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_auto_20190506_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaPrestacao',
            fields=[
                ('entrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Entrada')),
                ('recorrencia', models.PositiveIntegerField(default=0)),
                ('tipo_recorrencia', models.CharField(choices=[('1', 'Dias'), ('2', 'Meses'), ('3', 'Anos')], default='1', max_length=1)),
                ('primeiro_vencimento', models.DateField()),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('financeiro.entrada',),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='SaidaPrestacao',
            fields=[
                ('saida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Saida')),
                ('recorrencia', models.PositiveIntegerField(default=0)),
                ('tipo_recorrencia', models.CharField(choices=[('1', 'Dias'), ('2', 'Meses'), ('3', 'Anos')], default='1', max_length=1)),
                ('primeiro_vencimento', models.DateField()),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('financeiro.saida',),
        ),
    ]
