# Generated by Django 2.0.5 on 2019-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_entradaprestacao_parcela_saidaprestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='classificacao_dre',
            field=models.CharField(choices=[('1', 'Venda de produtos/mercadorias'), ('2', 'Venda de serviços'), ('3', 'Receita financeira'), ('4', 'Outra receita')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='saida',
            name='classificacao_dre',
            field=models.CharField(choices=[('1', 'Despesa com vendas'), ('2', 'Despesa administrativa'), ('3', 'Pró-labore'), ('4', 'Despesa financeira'), ('5', 'Outra despesa')], default='1', max_length=1),
        ),
    ]
