# Generated by Django 2.0.5 on 2019-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_auto_20190611_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='classificacao_dre',
            field=models.CharField(blank=True, choices=[('1', 'Venda de produtos/mercadorias'), ('2', 'Venda de serviços'), ('3', 'Receita financeira'), ('4', 'Outra receita')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='classificacao_dre',
            field=models.CharField(blank=True, choices=[('1', 'Despesa com vendas'), ('2', 'Despesa administrativa'), ('3', 'Pró-labore'), ('4', 'Despesa financeira'), ('5', 'Outra despesa')], max_length=1, null=True),
        ),
    ]
